### PR TITLE
Convert to Swift 5.0

### PR DESCRIPTION
**Pull request by farktronix**
No code changes required, so this is a simple one!

### CODE REVIEW

**Comment by Fryie** [comment]
Not that simple, unfortunately. The package is broken for installation with SPM and Swift 5 currently. Two things would be needed to change that:

Change the Package.swift to:
```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "CSwiftV",
    targets: [
      .target(
          name: "CSwiftV",
          dependencies: []
      )
    ]
)
```
and move all the files in `Sources/` into a new directory `Sources/CSwiftV`.
edit: as an alternative to moving the files, it might also be possible to specify a `path:` argument in `.target`, see: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#targets

This will probably mean that the Package won't be compatible with Swift 3, though (at least not through SPM), not sure if this can be fixed.

**Comment by farktronix** [comment]
@Fryie Thanks for catching that! Did Swift 5 introduce a new package layout? I'm confused about why package manager changes are also required.

**Comment by Fryie** [comment]
@farktronix As far as I understand it (I'm not an expert on this), this new layout (which includes having to explicity specify a target) was introduced in Swift 4. Swift 5 however drops the Swift 3 compatibility that was still available in Swift 4. If no `swift-tools-version` is provided, it defaults to 3 (for compatibility reasons).

**Comment by Daniel1of1** [comment]
Thanks for this @farktronix, @Fryie.

I pushed the `Package.swift` change up. I'll merge this in and do a 0.0.9 release.

**Comment by Daniel1of1** [comment]
I've published `0.0.9` to cocoa pods. Any thoughts on maintaining compatibility for multiple swift versions would be greatly appreciated 😊

**Pull request merged**
