### PR TITLE
Spring Cleaning and Performance Improvements

### PR DESCRIPTION
**Pull request by dennisweissmann**
File Structure:
- simplified the file structure and made it swiftpm-compliant
- deleted the explicit Test target and scheme and used the tests that come with each framework (you can now run the tests as usual with cmd+u)
- reused plists and headers for all targets

Code:
- changed the extension methods to computed properties
- cleaned up and simplified the code
- changed free functions to static functions on CSwiftV
- changed reduce in `split:` to an iterative version which improves performance by 36x from 180 seconds to 5 (I love reduce but if the accumulator is an array the array gets copied each time the closure is executed which sums up ...)
- changed the initializer's first label from "String" to "string"

Tests:
- added a performance test (simulate a csv string of 100k lines with 3 columns - that is my use case, can easily be changed)
# 

What I haven't done yet:
- increase CocoaPods version
- create tvOS target
- create swiftpm package file

### CODE REVIEW

**Comment by Daniel1of1** [comment]
👍 to _all_ changes, thanks a lot 🎉 . Good to have a performance test too. Was on my TODO list. I'll merge this as is, only thing I may change is the 100k lines, may reduce to 10k, since on my machine the high performing version is 48s 😄.

**Comment by Daniel1of1** [comment]
no probs on "what you haven't done" this is great 😄. Will get round to those at some point.

**Comment by dennisweissmann** [comment]
Thanks :) (and thanks for providing it, it's really a cool project 👍) Oh sorry, yeah that's a little too much then :D (didn't know my iMac was _that_ fast).

**Comment by dennisweissmann** [comment]
Another thing I forgot to mention I didn't do (because I didn't know if it's for a purpose I don't get):
There's also an executable target in there (but it doesn't compile since there's no application code anywhere). If it's not of any use you might want to delete it, too. :)

**Comment by Daniel1of1** [comment]
yep it's totally redundant at the moment :) removed.

**Comment by Daniel1of1** [comment]
all addressed as of c0d75ce thanks again for all the work. 👍

**Comment by dennisweissmann** [comment]
Awesome! 👍💯 You're welcome!

**Pull request merged**
